win: test.o
	gcc -o win test.o -lncurses
test.o: test.c
	gcc -c test.o test.c 

exam: example.o
	gcc -o exam example.o -lncurses
example.o: example.c
	gcc -c example.o example.c

test2: test2.o
	gcc -o test2 test2.o -lncurses
test2.o: test2.c
	gcc -c test2.o test2.c

window: window.o
	gcc -o window window.o -lncurses
window.o: window.c
	gcc -c window.o window.c

