win: test.o
	gcc -o win test.o -lncurses
test.o: test.c
	gcc -c test.o test.c 

exam: example.o
	gcc -o exam example.o -lncurses
example.o: example.c
	gcc -c example.o example.c

test2: test2.o
	gcc -o test2 test2.o -lncurses
test2.o: test2.c
	gcc -c test2.o test2.c

window: window.o
	gcc -o window window.o -lncurses
window.o: window.c
	gcc -c window.o window.c

window2: window2.o
	gcc -o window2 window2.o -lncurses
window2.o: window2.c
	gcc -c window2.o window2.c

color: color.o
	gcc -o color color.o -lncurses
color.o: color.c
	gcc -c color.o color.c

